Listen 8106

<VirtualHost *:8106>
    ServerName payment-card-service.transoft.bo
    ServerAlias payment-card-service.transoft.bo

    DocumentRoot /var/www/html/payment_card_service/public

    ErrorLog ${APACHE_LOG_DIR}/payment_card_service_error.log
    CustomLog ${APACHE_LOG_DIR}/payment_card_service_access.log combined

    <Directory /var/www/html/payment_card_service/public>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted

        RewriteEngine On
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^ index.php [L]
    </Directory>

    <FilesMatch \.php$>
        SetHandler application/x-httpd-php
    </FilesMatch>
</VirtualHost>

